---
- name: delete domain
  hosts: all
  become: yes

  tasks:
    - name: Delete a zanzibar.weatherhub.be A record to point to 127.0.0.1
      community.dns.hetzner_dns_record:
        state: absent
        zone: "{{ hetzner_zone }}"
        record: "{{ subdomain_name }}"
        type: A
        ttl: 7200
        value: "{{ ip_address }}"
        hetzner_token: "{{ hetzner_api_key }}"
